from transformers import BertTokenizer, BartForConditionalGeneration, Text2TextGenerationPipeline

tokenizer = BertTokenizer.from_pretrained("fnlp/bart-base-chinese")
model = BartForConditionalGeneration.from_pretrained("./summary_model")
text2text_generator = Text2TextGenerationPipeline(model, tokenizer)

# Manually skip wrong titles generated by the model.
SKIP_LIST = ["早报", "睡前曲", "新闻", "白岩松", "人物", "书单", "每日"]


def skip_title_check(title):
    for s in SKIP_LIST:
        if s in title:
            return False
    return True


def generate_title(s):
    src_len = 511
    candidate_results = []
    while src_len > 150 and len(candidate_results) < 5:
        output = text2text_generator(s[:src_len], max_length=64, do_sample=False)
        s = output[0]["generated_text"]
        # if skip_title_check(s) is False and s not in candidate_results:
        if s not in candidate_results:
            candidate_results.append(s)
        src_len -= 10
    return candidate_results
